/** @type {import('tailwindcss').Config} */

export default {
  content: [
    './src/**/*.{js,jsx,ts,tsx}',
    './.storybook/**/*.{js,jsx,ts,tsx}'
  ],
  darkMode: 'class',
  theme: {
    extend: {
        colors: {
            primary: "#2d4dff",
            violet: {
                50: "var(--colors-colors-violet-50)",
                100: "var(--colors-colors-violet-100)",
                200: "var(--colors-colors-violet-200)",
                300: "var(--colors-colors-violet-300)",
                400: "var(--colors-colors-violet-400)",
                500: "var(--colors-colors-violet-500)",
                600: "var(--colors-colors-violet-600)",
                700: "var(--colors-colors-violet-700)",
                800: "var(--colors-colors-violet-800)",
                900: "var(--colors-colors-violet-900)",
            },
            teal: {
                50: "var(--colors-colors-teal-50)",
                100: "var(--colors-colors-teal-100)",
                200: "var(--colors-colors-teal-200)",
                300: "var(--colors-colors-teal-300)",
                400: "var(--colors-colors-teal-400)",
                500: "var(--colors-colors-teal-500)",
                600: "var(--colors-colors-teal-600)",
                700: "var(--colors-colors-teal-700)",
                800: "var(--colors-colors-teal-800)",
                900: "var(--colors-colors-teal-900)",
            },
            blue: {
                50: "var(--colors-colors-blue-50)",
                100: "var(--colors-colors-blue-100)",
                200: "var(--colors-colors-blue-200)",
                300: "var(--colors-colors-blue-300)",
                400: "var(--colors-colors-blue-400)",
                500: "var(--colors-colors-blue-500)",
                600: "var(--colors-colors-blue-600)",
                700: "var(--colors-colors-blue-700)",
                800: "var(--colors-colors-blue-800)",
                900: "var(--colors-colors-blue-900)",
            },
            yellow: {
                50: "var(--colors-colors-yellow-50)",
                100: "var(--colors-colors-yellow-100)",
                200: "var(--colors-colors-yellow-200)",
                300: "var(--colors-colors-yellow-300)",
                400: "var(--colors-colors-yellow-400)",
                500: "var(--colors-colors-yellow-500)",
                600: "var(--colors-colors-yellow-600)",
                700: "var(--colors-colors-yellow-700)",
                800: "var(--colors-colors-yellow-800)",
                900: "var(--colors-colors-yellow-900)",
            },
            red: {
                50: "var(--colors-colors-red-50)",
                100: "var(--colors-colors-red-100)",
                200: "var(--colors-colors-red-200)",
                300: "var(--colors-colors-red-300)",
                400: "var(--colors-colors-red-400)",
                500: "var(--colors-colors-red-500)",
                600: "var(--colors-colors-red-600)",
                700: "var(--colors-colors-red-700)",
                800: "var(--colors-colors-red-800)",
                900: "var(--colors-colors-red-900)",
            },
            green: {
                50: "var(--colors-colors-green-50)",
                100: "var(--colors-colors-green-100)",
                200: "var(--colors-colors-green-200)",
                300: "var(--colors-colors-green-300)",
                400: "var(--colors-colors-green-400)",
                500: "var(--colors-colors-green-500)",
                600: "var(--colors-colors-green-600)",
                700: "var(--colors-colors-green-700)",
                800: "var(--colors-colors-green-800)",
                900: "var(--colors-colors-green-900)",
            },
            gray: {
                50: "var(--colors-colors-gray-50)",
                100: "var(--colors-colors-gray-100)",
                200: "var(--colors-colors-gray-200)",
                300: "var(--colors-colors-gray-300)",
                400: "var(--colors-colors-gray-400)",
                500: "var(--colors-colors-gray-500)",
                600: "var(--colors-colors-gray-600)",
                700: "var(--colors-colors-gray-700)",
                800: "var(--colors-colors-gray-800)",
                900: "var(--colors-colors-gray-900)",
            },
            purple: {
                50: "var(--colors-colors-purple-50)",
                100: "var(--colors-colors-purple-100)",
                200: "var(--colors-colors-purple-200)",
                300: "var(--colors-colors-purple-300)",
                400: "var(--colors-colors-purple-400)",
                500: "var(--colors-colors-purple-500)",
                600: "var(--colors-colors-purple-600)",
                700: "var(--colors-colors-purple-700)",
                800: "var(--colors-colors-purple-800)",
                900: "var(--colors-colors-purple-900)",
            },
            alpha: {
                '00': "var(--colors-colors-alpha-00)",
                50: "var(--colors-colors-alpha-50)", 
                100: "var(--colors-colors-alpha-100)",
                200: "var(--colors-colors-alpha-200)",
                300: "var(--colors-colors-alpha-300)",
                400: "var(--colors-colors-alpha-400)",
                500: "var(--colors-colors-alpha-500)",
                600: "var(--colors-colors-alpha-600)",
                700: "var(--colors-colors-alpha-700)",
                800: "var(--colors-colors-alpha-800)",
                900: "var(--colors-colors-alpha-900)",
            },
            rose: {
                50: "var(--colors-colors-rose-50)",
                100: "var(--colors-colors-rose-100)",
                200: "var(--colors-colors-rose-200)",
                300: "var(--colors-colors-rose-300)",
                400: "var(--colors-colors-rose-400)",
                500: "var(--colors-colors-rose-500)",
                600: "var(--colors-colors-rose-600)",
                700: "var(--colors-colors-rose-700)",
                800: "var(--colors-colors-rose-800)",
                900: "var(--colors-colors-rose-900)",
            },
            pink: {
                50: "var(--colors-colors-pink-50)",
                100: "var(--colors-colors-pink-100)",
                200: "var(--colors-colors-pink-200)",
                300: "var(--colors-colors-pink-300)",
                400: "var(--colors-colors-pink-400)",
                500: "var(--colors-colors-pink-500)",
                600: "var(--colors-colors-pink-600)",
                700: "var(--colors-colors-pink-700)",
                800: "var(--colors-colors-pink-800)",
                900: "var(--colors-colors-pink-900)",
            },
            orange: {
                50: "var(--colors-colors-orange-50)",
                100: "var(--colors-colors-orange-100)",
                200: "var(--colors-colors-orange-200)",
                300: "var(--colors-colors-orange-300)",
                400: "var(--colors-colors-orange-400)",
                500: "var(--colors-colors-orange-500)",
                600: "var(--colors-colors-orange-600)",
                700: "var(--colors-colors-orange-700)",
                800: "var(--colors-colors-orange-800)",
                900: "var(--colors-colors-orange-900)",
            },
            metal: {
                50: "var(--colors-colors-metal-50)",
                100: "var(--colors-colors-metal-100)",
                200: "var(--colors-colors-metal-200)",
                300: "var(--colors-colors-metal-300)",
                400: "var(--colors-colors-metal-400)",
                500: "var(--colors-colors-metal-500)",
                600: "var(--colors-colors-metal-600)",
                700: "var(--colors-colors-metal-700)",
                800: "var(--colors-colors-metal-800)",
                900: "var(--colors-colors-metal-900)",
            },
            lime: {
                50: "var(--colors-colors-lime-50)",
                100: "var(--colors-colors-lime-100)",
                200: "var(--colors-colors-lime-200)",
                300: "var(--colors-colors-lime-300)",
                400: "var(--colors-colors-lime-400)",
                500: "var(--colors-colors-lime-500)",
                600: "var(--colors-colors-lime-600)",
                700: "var(--colors-colors-lime-700)",
                800: "var(--colors-colors-lime-800)",
                900: "var(--colors-colors-lime-900)",
            },
            'sky-blue': {
                50: "var(--colors-colors-sky-blue-50)",
                100: "var(--colors-colors-sky-blue-100)",
                200: "var(--colors-colors-sky-blue-200)",
                300: "var(--colors-colors-sky-blue-300)",
                400: "var(--colors-colors-sky-blue-400)",
                500: "var(--colors-colors-sky-blue-500)",
                600: "var(--colors-colors-sky-blue-600)",
                700: "var(--colors-colors-sky-blue-700)",
                800: "var(--colors-colors-sky-blue-800)",
                900: "var(--colors-colors-sky-blue-900)",
            },
            indigo: {
                50: "var(--colors-colors-indigo-50)",
                100: "var(--colors-colors-indigo-100)",
                200: "var(--colors-colors-indigo-200)",
                300: "var(--colors-colors-indigo-300)",
                400: "var(--colors-colors-indigo-400)",
                500: "var(--colors-colors-indigo-500)",
                600: "var(--colors-colors-indigo-600)",
                700: "var(--colors-colors-indigo-700)",
                800: "var(--colors-colors-indigo-800)",
                900: "var(--colors-colors-indigo-900)",
            },
            fuchsia: {
                50: "var(--colors-colors-fuchsia-50)",
                100: "var(--colors-colors-fuchsia-100)",
                200: "var(--colors-colors-fuchsia-200)",
                300: "var(--colors-colors-fuchsia-300)",
                400: "var(--colors-colors-fuchsia-400)",
                500: "var(--colors-colors-fuchsia-500)",
                600: "var(--colors-colors-fuchsia-600)",
                700: "var(--colors-colors-fuchsia-700)",
                800: "var(--colors-colors-fuchsia-800)",
                900: "var(--colors-colors-fuchsia-900)",
            },
            emerald: {
                50: "var(--colors-colors-emerald-50)",
                100: "var(--colors-colors-emerald-100)",
                200: "var(--colors-colors-emerald-200)",
                300: "var(--colors-colors-emerald-300)",
                400: "var(--colors-colors-emerald-400)",
                500: "var(--colors-colors-emerald-500)",
                600: "var(--colors-colors-emerald-600)",
                700: "var(--colors-colors-emerald-700)",
                800: "var(--colors-colors-emerald-800)",
                900: "var(--colors-colors-emerald-900)",
            },
            cyan: {
                50: "var(--colors-colors-cyan-50)",
                100: "var(--colors-colors-cyan-100)",
                200: "var(--colors-colors-cyan-200)",
                300: "var(--colors-colors-cyan-300)",
                400: "var(--colors-colors-cyan-400)",
                500: "var(--colors-colors-cyan-500)",
                600: "var(--colors-colors-cyan-600)",
                700: "var(--colors-colors-cyan-700)",
                800: "var(--colors-colors-cyan-800)",
                900: "var(--colors-colors-cyan-900)",
            },
            bronze: {
                50: "var(--colors-colors-bronze-50)",
                100: "var(--colors-colors-bronze-100)",
                200: "var(--colors-colors-bronze-200)",
                300: "var(--colors-colors-bronze-300)",
                400: "var(--colors-colors-bronze-400)",
                500: "var(--colors-colors-bronze-500)",
                600: "var(--colors-colors-bronze-600)",
                700: "var(--colors-colors-bronze-700)",
                800: "var(--colors-colors-bronze-800)",
                900: "var(--colors-colors-bronze-900)",
            },
            'blue-gray': {
                50: "var(--colors-colors-blue-gray-50)",
                100: "var(--colors-colors-blue-gray-100)",
                200: "var(--colors-colors-blue-gray-200)",
                300: "var(--colors-colors-blue-gray-300)",
                400: "var(--colors-colors-blue-gray-400)",
                500: "var(--colors-colors-blue-gray-500)",
                600: "var(--colors-colors-blue-gray-600)",
                700: "var(--colors-colors-blue-gray-700)",
                800: "var(--colors-colors-blue-gray-800)",
                900: "var(--colors-colors-blue-gray-900)",
            },
        },
        fontSize: {
            'large-title': ['34px', {
                lineHeight: '41px',
            }],
            'title-1': ['28px', {
                lineHeight: '34px',
            }],
            'title-2': ['22px', {
                lineHeight: '28px',
            }],
            'title-3': ['20px', {
                lineHeight: '25px',
            }],
            'headline': ['17px', {
                lineHeight: '22px',
            }],
            'body': ['17px', {
                lineHeight: '22px',
            }],
            'callout': ['16px', {
                lineHeight: '21px',
            }],
            'footnote': ['13px', {
                lineHeight: '18px',
            }],
            'caption-1': ['12px', {
                lineHeight: '16px',
            }],
            'caption-2': ['11px', {
                lineHeight: '13px',
            }],
        },
    },
  },
  plugins: []
}

